# Generated by Django 3.1.7 on 2021-04-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210429_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategories',
            name='image',
            field=models.FileField(upload_to='media'),
        ),
    ]
