# Generated by Django 3.1.7 on 2021-06-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
