# Generated by Django 3.1.7 on 2021-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_items_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('image_url', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
