# Generated by Django 3.1.7 on 2021-06-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210619_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategories',
            name='title',
        ),
    ]
